---

- hosts: all

  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
  - name: apt install needed software
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python', 'python3', 'python-pip', 'python3-pip', 'virtualenv', 'python-setuptools', 'python3-setuptools']
  - name: install needed software
    block:
      - name: pip docker
        pip:
          name: docker
          state: latest
        become: yes
      - name: pip docker-compose
        pip:
          name: docker-compose
          state: latest
        become: yes
