---
- hosts: workers

  vars:
    default_save_path: /home/Zilk/vars.yml
    default_owner: Zilk
    default_group: Zilk
    own_ip: "{{ ansible_facts.eth0.ipv4.address }}"

  tasks:
    - name: Copy Remote-To-Remote (from serverA to serverB)
      synchronize:
        src: "{{ default_save_path }}"
        dest: "{{ default_save_path }}"
      delegate_to: managers
