---
- hosts: workers

  tasks:        
    - name: copy vars.yml to workers
      copy:
        src: /home/Loek/manager-01/home/Zilk/vars.yml
        dest: /home/Zilk/vars.yml
        remote_src: yes
