---
- hosts: workers

  vars:
    default_save_path: /home/Zilk/vars.yml
    own_ip: "{{ ansible_facts.eth0.ipv4.address }}"

  tasks:
    - name: copy vars.yml to workers
      copy:
        src: /home/Loek/manager-01/home/Zilk/vars.yml
        dest: "{{ default_save_path }}"
    
    - name: Include vars of vars.yaml into the 'vars'
      include_vars:
        file: "{{ default_save_path }}"
        name: vars

    - name: Remove potential existing swarm hosts
      docker_swarm:
        state: absent
        force: true
      become: yes

    - name: Add nodes
      docker_swarm:
        state: join
        advertise_addr: "{{ own_ip }}"
        join_token: vars.frank
        remote_addrs: vars.tiffany
      become: yes
