---
- hosts: managers

  tasks:   
        
    - name: Log into private registry and force re-authorization
      docker_login:
        registry: sharedregistry.azurecr.io
        username: 465b25fb-66ed-40b4-ad5e-69153681991b
        password: bda62a70-76aa-4c67-80a9-b4e7c1ef3b20

    - name: pull loekamy image
      docker_image:
        name: nginx
        source: pull
      
    - name: Remove service
      docker_swarm_service:
        name: my_web
        state: absent
      
    - name: create docker service visualizer
      command: docker service create --name=my_web --replicas=3 --publish=80:80/tcp nginx
      become: yes
